"""
This module contains constants.
"""
import os


ABTESTS_TABLE = os.environ["ABTESTS_TABLE"]
REMOTE_CONFIGS_TABLE = os.environ["REMOTE_CONFIGS_TABLE"]
REMOTE_CONFIGS_OVERRIDES_TABLE = os.environ["REMOTE_CONFIGS_OVERRIDES_TABLE"]
USERS_ABTESTS_TABLE = os.environ["USERS_ABTESTS_TABLE"]
USERS_AUDIENCES_TABLE = os.environ["USERS_AUDIENCES_TABLE"]
