openapi: 3.0.3
info:
  version: 1.0.0
  title: GEODE REST API - Analytics Backoffice
  description: |-
    - **[Development URL](https://apidev.geode.com/analytics-backoffice)**
    - **[Production URL](https://api.geode.com/analytics-backoffice)**

servers:
- url: https://apidev.geode.com/analytics-backoffice
tags:
- name: Applications
  description: Handle GEODE Analytics Applications
- name: ABTests
  description: Handle GEODE ABTests
- name: Audiences
  description: Handle GEODE Audiences
- name: Remote Configs
  description: Handle GEODE Remote Configs and Overrides

paths:

  #  ----- Applications ----------------------------------

  /applications:
    get:
      summary: Get Applications
      description: This endpoint returns GEODE analytics applications.
      tags:
      - Applications
      responses:
        200:
          description: Applications returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    application_ID:
                      type: string
                      example: android.com.geode.dazzly.dev
                    application_name:
                      type: string
                      example: dazzly_android_dev
                    created_at:
                      type: string
                      example: 2023-09-21T14:56:06Z
                    description:
                      type: string
                      example: Dazzly Android DEV
                    updated_at:
                      type: string
                      example: 2023-09-21T14:56:06Z

  /applications/{application_ID}/events:
    get:
      summary: Get latest events from application_ID
      description: This endpoint returns latest events from application_ID.
      tags:
      - Applications
      parameters:
      - name: application_ID
        in: path
        description: ID of the GEODE analytics application
        required: true
        schema:
          type: string
          example: android.com.geode.dazzly.dev
      - name: limit
        in: query
        description: Number of desired events. It should be integer and greater than 0. Its default value is **50**.
        required: true
        schema:
          type: number
          example: 50
      responses:
        200:
          description: Applications returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    app_info:
                      type: string
                      example: "{\"app_version\":\"1.1.48\",\"build_number\":\"7203\",\"unity_version\":\"2021.3.31f1\"}"
                    application_name:
                      type: string
                      example: dazzly_android_dev
                    day:
                      type: string
                      example: 16
                    device:
                      type: string
                      example: "{\"advertising_id\":\"11a2a8d9-d809-4b3d-ab1d-e91270898f4d\",\"battery_load\":0.2,\"battery_status\":\"Discharging\",\"category\":\"mobile\",\"is_limiting_ad_tracking\":false,\"language\":\"en\",\"model_name\":\"Google Pixel 5\",\"os_version\":\"Android OS 13 / API-33 (TQ3A.230901.001/10750268)\",\"platform\":\"android\"}"
                    event_data:
                      type: string
                      example: "{\"ad_format\":\"rewarded\",\"geode_ad_geode_id\":\"Match_September_01_Portrait_30s\"}"
                    event_id:
                      type: string
                      example: ff95d64b-f86d-47d5-868c-9d844ff3530a
                    event_name:
                      type: string
                      example: geode_will_display_geode_ad
                    event_timestamp:
                      type: string
                      example: 1697449531
                    event_type:
                      type: string
                      example: custom
                    event_version:
                      type: string
                      example: v1
                    game_time:
                      type: string
                      example: 2095
                    metadata:
                      type: string
                      example: "{\"api\":{\"request_id\":\"1798aef6-8e26-4d51-beee-8c237efcc834\",\"request_time_epoch\":1697449546113},\"ingestion_id\":\"b366eaf9-d314-410e-b3ed-72f3df121bcd\",\"processing_result\":{\"status\":\"ok\"},\"processing_timestamp\":1697449607}"
                    month:
                      type: string
                      example: 10
                    remote_config:
                      type: string
                      example: "{\"iapPricing\":{\"value\":\"{\\\"group\\\":\\\"adsT3subT3\\\",\\\"weekly\\\":{\\\"id\\\":\\\"com.geode.dazzlymerge.dev.weekly.tier3\\\",\\\"type\\\":\\\"Subscription\\\"},\\\"monthly\\\":{\\\"id\\\":\\\"com.geode.dazzlymerge.dev.monthly.tier3\\\",\\\"type\\\":\\\"Subscription\\\"},\\\"yearly\\\":{\\\"id\\\":\\\"com.geode.dazzlymerge.dev.yearly.tier3\\\",\\\"type\\\":\\\"Subscription\\\"},\\\"noads\\\":{\\\"id\\\":\\\"com.geode.dazzlymerge.dev.noads.tier3\\\",\\\"type\\\":\\\"NonConsumable\\\"}}\",\"value_origin\":\"abtest\"},\"showDazzlyMatchBanner\":{\"value\":\"true\",\"value_origin\":\"reference_value\"},\"skipOnboarding\":{\"value\":\"noSkip\",\"value_origin\":\"abtest\"}}"
                    user:
                      type: string
                      example: "{\"country\":\"FR\",\"ip_adress\":\"89.91.64.155\",\"num_total_session\":16,\"session_id\":\"11fb8911-d45e-4814-9443-786f134309fe\",\"start_first_session_date\":1695395597,\"start_session_date\":1697449447,\"user_id\":\"05e5ff99-48be-4aa9-b763-b5f3eaed3081\"}"
                    year:
                      type: string
                      example: 2023
        400:
          description: Events canNOT be retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  #  ----- ABTests ----------------------------------

  /abtests:
    get:
      summary: Get all ABTests
      description: This endpoint returns all ABTests.
      tags:
      - ABTests
      responses:
        200:
          description: ABTests returned successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /abtests/{abtest_name}:
    post:
      summary: Set ABTest
      description: This endpoint sets ABTest.
      tags:
      - ABTests
      parameters:
      - name: abtest_name
        in: path
        description: name of the ABTest
        required: true
        schema:
          type: string
          example: LightColors
      requestBody:
        description: |-
          - `abtest_name` is the unique ABTest identifier.
          - `target_user_percent` must be between 0 and 100.
        required: true
        content:
          application/json:
            schema:
              required:
              - target_user_percent
              - variants
              type: object
              properties:
                target_user_percent:
                  type: integer
                  example: 100
                variants:
                  type: array
                  item:
                    type: string
                  example:
                  - Blue
                  - Yellow
      responses:
        204:
          description: The ABTest was created/updated successfully.
        400:
          description: The ABTest has NOT been created/updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
    delete:
      summary: Delete ABTest
      description: This endpoint deletes ABTest. You can't delete ABTest link with Remote Config Override.
      tags:
      - ABTests
      parameters:
      - name: abtest_name
        in: path
        description: name of the ABTest
        required: true
        schema:
          type: string
          example: LightColors
      responses:
        204:
          description: The ABTest was deleted successfully.
        400:
          description: The ABTest has NOT been deleted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /abtests/{abtest_name}/promote:
    post:
      summary: Promote ABTest
      description: This endpoint promotes ABTest. It promotes value to Remote Config Override Audience. If Audience is ALL, it replaces reference_value of Remote Config.
      tags:
      - ABTests
      parameters:
      - name: abtest_name
        in: path
        description: name of the ABTest
        required: true
        schema:
          type: string
          example: LightColors
      requestBody:
        description: |-
          - `promoted_value` should be reference_value of Remote Config or a variant of ABTest.
        required: true
        content:
          application/json:
            schema:
              required:
              - remote_config_name
              - audience_name
              - promoted_value
              type: object
              properties:
                remote_config_name:
                  type: string
                  example: ColorButton
                audience_name:
                  type: string
                  example: ONLY_FR
                promoted_value:
                  type: string
                  example: Blue
      responses:
        204:
          description: The ABTest was promoted successfully.
        400:
          description: The ABTest has NOT been promoted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  #  ----- Audience ----------------------------------

  /audiences:
    get:
      summary: Get all Audiences
      description: This endpoint returns all Audiences.
      tags:
      - Audiences
      responses:
        200:
          description: Audiences returned successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /audiences/{audience_name}:
    post:
      summary: Set Audience
      description: This endpoint sets Audience.
      tags:
      - Audiences
      parameters:
      - name: audience_name
        in: path
        description: name of the Audience
        required: true
        schema:
          type: string
          example: ONLY_FR
      requestBody:
        description: |-
          - `promoted_value` should be reference_value of Remote Config or a variant of ABTest.
        required: true
        content:
          application/json:
            schema:
              required:
              - condition_type
              - condition_value
              - description
              type: object
              properties:
                condition_type:
                  type: string
                  example: target_countries
                condition_value:
                  type: string
                  example: "Should be Any type"
                description:
                  type: string
                  example: This Audience targets only French players
      responses:
        204:
          description: The Audience was created/updated successfully.
        400:
          description: The Audience has NOT been created/updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
    delete:
      summary: Delete Audience
      description: This endpoint deletes Audience.
      tags:
      - Audiences
      parameters:
      - name: audience_name
        in: path
        description: name of the Audience
        required: true
        schema:
          type: string
          example: ONLY_FR
      responses:
        204:
          description: The Audience was deleted successfully.
        400:
          description: The Audience has NOT been deleted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  #  ----- Remote Configs ----------------------------------

  /remote-configs:
    get:
      summary: Get all Remote Configs
      description: This endpoint returns all Remote Configs.
      tags:
      - Remote Configs
      responses:
        200:
          description: Remote Configs returned successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /remote-configs/{remote_config_name}:
    post:
      summary: Set Remote Config
      description: This endpoint sets Remote Config.
      tags:
      - Remote Configs
      parameters:
      - name: remote_config_name
        in: path
        description: name of the Remote Config
        required: true
        schema:
          type: string
          example: ColorButton
      requestBody:
        description: |-
          - `remote_config_name` is the unique Remote Config identifier.
        required: true
        content:
          application/json:
            schema:
              required:
              - description
              - reference_value
              type: object
              properties:
                description:
                  type: string
                  example: This Remote Config allows to handle color button.
                reference_value:
                  type: string
                  example: Blue
      responses:
        204:
          description: The Remote Config was created/updated successfully.
        400:
          description: The Remote Config has NOT been created/updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /remote-configs/{remote_config_name}/override/{audience_name}:
    post:
      summary: Set Remote Config Override
      description: This endpoint sets Override for a Remote Config based on an Audience. If user matches all Audience conditions, it will retrieve override_value instead of reference_value, ONLY if override_type == fixed. If override_type == abtest, override_value should be abtest_name.
      tags:
      - Remote Configs
      parameters:
      - name: remote_config_name
        in: path
        description: name of the Remote Config
        required: true
        schema:
          type: string
          example: ColorButton
      - name: audience_name
        in: path
        description: name of the Audience
        required: true
        schema:
          type: string
          example: ONLY_FR
      requestBody:
        description: |-
          - You can't update activated Remote Config Override
          - You can't link ABTest to multiple Remote Config Override
        required: true
        content:
          application/json:
            schema:
              required:
              - override_type
              - override_value
              type: object
              properties:
                override_type:
                  type: string
                  enum:
                  - abtest
                  - fixed
                override_value:
                  type: string
                  example: LightColors
      responses:
        204:
          description: The Remote Config Override was created/updated successfully.
        400:
          description: The Remote Config Override has NOT been created/updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
    delete:
      summary: Delete Remote Config Override
      description: This endpoint deletes Override for a Remote Config based on an Audience. You can't delete activated Remote Config Override.
      tags:
      - Remote Configs
      parameters:
      - name: remote_config_name
        in: path
        description: name of the Remote Config
        required: true
        schema:
          type: string
          example: ColorButton
      - name: audience_name
        in: path
        description: name of the Audience
        required: true
        schema:
          type: string
          example: ONLY_FR
      responses:
        204:
          description: The Remote Config Override was deleted successfully.
        400:
          description: The Remote Config Override has NOT been deleted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /remote-configs/{remote_config_name}/override/{audience_name}/activate:
    post:
      summary: Activate Remote Config Override
      description: This endpoint activates Override for a Remote Config based on an Audience.
      tags:
      - Remote Configs
      parameters:
      - name: remote_config_name
        in: path
        description: name of the Remote Config
        required: true
        schema:
          type: string
          example: ColorButton
      - name: audience_name
        in: path
        description: name of the Audience
        required: true
        schema:
          type: string
          example: ONLY_FR
      requestBody:
        description: |-
          - If override_type == fixed, you can deactivate Remote Config Override. It will be added to the Remote Configs Override History.
          - If override_type == abtest, you can't deactivate Remote Config Override. You need to call the endpoint /abtests/{abtest_name}/promote
        required: true
        content:
          application/json:
            schema:
              required:
              - activated
              type: object
              properties:
                activated:
                  type: boolean
      responses:
        204:
          description: The Remote Config Override was activated successfully.
        400:
          description: The Remote Config Override has NOT been activated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

components:
  schemas:
    errorResponse:
      type: object
      properties:
        error:
          type: string
          example: Description of the error...
