"""
This module contains constants.
"""
import os


ANALYTICS_BUCKET = os.environ["ANALYTICS_BUCKET"]
ANALYTICS_DATABASE = os.environ["ANALYTICS_DATABASE"]
ANALYTICS_TABLE = os.environ["ANALYTICS_TABLE"]

AUDIENCES_TABLE = os.environ["AUDIENCES_TABLE"]
USERS_AUDIENCES_TABLE = os.environ["USERS_AUDIENCES_TABLE"]
